# based on Danielle Navarro's work: https://github.com/djnavarro/arch-r/blob/main/.github/workflows/build-image.yaml
# also inspired by organization of Posit's r-docker project: https://github.com/rstudio/r-docker
name: Publish images

on:
  push:
    branches: ['main']
    
env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        level: [base]
        dist: [focal]    
    
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Enable multiple architectures
        uses: docker/setup-qemu-action@v2

      - name: Create temporary buildx builder
        uses: docker/setup-buildx-action@v2

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata 
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}-${{ matrix.level }}
          flavor:
            suffix: -${{ matrix.dist }}
          tags:
            type=edge

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          platforms: "linux/amd64,linux/arm64"
          context: ./${{ matrix.level }}/${{ matrix.dist }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
