name: Orchestrate - Build and Push

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-push-by-level:
    runs-on: ubuntu-latest  

    strategy:
      fail-fast: false
      matrix:
        dist: ['focal', 'jammy']    
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build base image
        uses: ./.github/workflows/build-push-image.yml
        with:
          level: base
          dist: ${{ matrix.dist }}
      
      - name: Build inst image
        uses: ./.github/workflows/build-push-image.yml
        with:
          level: inst
          dist: ${{ matrix.dist }}        