name: Orchestrate - Build and Push

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  base:
    uses: ./.github/workflows/build-push-image.yml
    with:
      level: base
    permissions:
      contents: read
      packages: write

  inst:
    needs: base
    uses: ./.github/workflows/build-push-image.yml
    with:
      level: inst
    permissions:
      contents: read
      packages: write
       